var groups = {
    "theCityAndtheCity": {
        "Anan MA": [
            "./extra/week_1.png",
            "content/group_A/Anan MA/week_1/processed/2_pr..png",
            "content/group_A/Anan MA/week_1/processed/3_pr..png",
            "content/group_A/Anan MA/week_1/processed/4_pr..png",
            "content/group_A/Anan MA/week_1/processed/5_pr..png",
            "content/group_A/Anan MA/week_1/processed/11_pr..png",
            "content/group_A/Anan MA/week_1/processed/Untitled-1_pr..jpg",
            "content/group_A/Anan MA/week_1/processed/Untitled-12_pr..png",
            "./extra/foo_week_1.png",
            "content/group_A/Anan MA/week_1/processed/b90cad34846b33ddd1e7620c0dbaa41_pr..png",
            "content/group_A/Anan MA/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Beining Zhang": [
            "./extra/week_1.png",
            "content/group_A/Beining Zhang/week_1/processed/3721cb3a5a9c3d051aeb00f2a9b0547_pr..png",
            "content/group_A/Beining Zhang/week_1/processed/c7f32408a681ea0f4359f74711cf62d_pr..png",
            "content/group_A/Beining Zhang/week_1/processed/ee270ce8860f597366b0ca303cf2997_pr..png",
            "content/group_A/Beining Zhang/week_1/processed/f1766f061879f376a7537210bd37c18_pr..png",
            "./extra/foo_week_1.png",
            "content/group_A/Beining Zhang/week_1/processed/d1e28f589c0bca6bee9cefaf08dc712_pr..jpg",
            "content/group_A/Beining Zhang/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Guangyao Cao": [
            "./extra/week_1.png",
            "content/group_A/Guangyao Cao/week_1/processed/image2_pr..png",
            "content/group_A/Guangyao Cao/week_1/processed/image_pr..png",
            "content/group_A/Guangyao Cao/week_1/processed/img3_pr..png",
            "content/group_A/Guangyao Cao/week_1/processed/img4_pr..png",
            "content/group_A/Guangyao Cao/week_1/processed/img5_pr..png",
            "content/group_A/Guangyao Cao/week_1/processed/img6_pr..png",
            "content/group_A/Guangyao Cao/week_1/processed/img7_pr..png",
            "./extra/foo_week_1.png",
            "content/group_A/Guangyao Cao/week_1/processed/introduction_pr.png",
            "content/group_A/Guangyao Cao/week_1/processed/\u5fae\u4fe1\u56fe\u7247_20220217151510_pr..jpg",
            "./extra/ref_week_1.png"
        ],
        "Yitong Xie": [
            "./extra/week_1.png",
            "content/group_A/Yitong Xie/week_1/processed/1_pr..jpg",
            "content/group_A/Yitong Xie/week_1/processed/2_pr..jpg",
            "content/group_A/Yitong Xie/week_1/processed/dinnimg - \u526f\u672c_pr..png",
            "content/group_A/Yitong Xie/week_1/processed/front_pr..png",
            "content/group_A/Yitong Xie/week_1/processed/s_pr..png",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-2_pr..jpg",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-22_pr..jpg",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-23_pr..jpg",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-24_pr..jpg",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-25_pr..jpg",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-2222_pr..jpg",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-2333_pr..jpg",
            "./extra/foo_week_1.png",
            "content/group_A/Yitong Xie/week_1/processed/introduction_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u5fae\u4fe1\u56fe\u7247_20230715151239_pr..jpg",
            "./extra/ref_week_1.png"
        ],
        "Yuxin Zhou": [
            "./extra/week_1.png",
            "content/group_A/Yuxin Zhou/week_1/processed/i2_pr..png",
            "content/group_A/Yuxin Zhou/week_1/processed/i3_pr..png",
            "content/group_A/Yuxin Zhou/week_1/processed/i4_pr..png",
            "content/group_A/Yuxin Zhou/week_1/processed/image_pr..png",
            "./extra/foo_week_1.png",
            "content/group_A/Yuxin Zhou/week_1/processed/d0e710c98440073df6ab70d4fee052a_pr..jpg",
            "content/group_A/Yuxin Zhou/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Deling Han": [
            "./extra/week_1.png",
            "content/group_B/Deling Han/week_1/processed/4e00c738eda32361cad5fd2a2232190_pr..png",
            "content/group_B/Deling Han/week_1/processed/46d29502859720bfde64c034e3cc2d8_pr..png",
            "content/group_B/Deling Han/week_1/processed/56e6a58851b67a9f1ab0a4f22b32436_pr..png",
            "content/group_B/Deling Han/week_1/processed/89dd8352e550dd55eae4ec0ae1eef95_pr..png",
            "content/group_B/Deling Han/week_1/processed/e1aef1425f4706180a44dca9d590c04_pr..png",
            "content/group_B/Deling Han/week_1/processed/e6b48c4807659b82e67f2ec0d0dddf6_pr..png",
            "./extra/foo_week_1.png",
            "content/group_B/Deling Han/week_1/processed/843136be438e87d628f9e240407bf4d_pr..jpg",
            "content/group_B/Deling Han/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Junren  Xian": [
            "./extra/week_1.png",
            "content/group_B/Junren  Xian/week_1/processed/\u5e7b\u706f\u72471_pr..PNG",
            "content/group_B/Junren  Xian/week_1/processed/\u5e7b\u706f\u72472_pr..PNG",
            "./extra/foo_week_1.png",
            "content/group_B/Junren  Xian/week_1/processed/88c929c2ea822d00937e7807557326a_pr..jpg",
            "content/group_B/Junren  Xian/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Shutong Guo": [
            "./extra/week_1.png",
            "content/group_B/Shutong Guo/week_1/processed/6c74d47ad19fa90f9cdba3e2883c9df_pr..png",
            "content/group_B/Shutong Guo/week_1/processed/dee117d1beccb8692c7c41766f5379e_pr..jpg",
            "./extra/foo_week_1.png",
            "content/group_B/Shutong Guo/week_1/processed/07a689347e9a41b0ec9ef5758210a10_pr..jpg",
            "content/group_B/Shutong Guo/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Wenxin Dai": [
            "./extra/week_1.png",
            "content/group_B/Wenxin Dai/week_1/processed/43a556224f29446a65e8c0fb5a8f4f7_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/191b998cee21ba2ed849b3e19dfe014_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/661998a365505a328d4916270a60987_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/243926565802691657_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/386026712471590118_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/410194747653042432_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/BIRKENHEAD FUTURE PLAN_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/adfd296495a366b3374eff6f4eff84f_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/babac12bb3d4b57821210ce5c87fcdf_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/c4b8ca337985b340d667abcd55a2846_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/d96a5f912e39c1d351930fc23e71b93_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/ea797b6b8d728c8a47a48295570cf6d_pr..png",
            "./extra/foo_week_1.png",
            "content/group_B/Wenxin Dai/week_1/processed/587438218396611271_pr..jpg",
            "content/group_B/Wenxin Dai/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Xinrui Ni": [
            "./extra/week_1.png",
            "content/group_B/Xinrui Ni/week_1/processed/2_pr..png",
            "content/group_B/Xinrui Ni/week_1/processed/4_pr..png",
            "content/group_B/Xinrui Ni/week_1/processed/i4_pr..png",
            "content/group_B/Xinrui Ni/week_1/processed/\u672a\u6807\u9898-1_pr..png",
            "./extra/foo_week_1.png",
            "content/group_B/Xinrui Ni/week_1/processed/IMG_0012(20230219-194931)_pr..JPG",
            "content/group_B/Xinrui Ni/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Jiayu Sun": [
            "./extra/week_1.png",
            "content/group_C/Jiayu Sun/week_1/processed/i7_pr..png",
            "content/group_C/Jiayu Sun/week_1/processed/i8_pr..png",
            "content/group_C/Jiayu Sun/week_1/processed/i9_pr..png",
            "./extra/foo_week_1.png",
            "content/group_C/Jiayu Sun/week_1/processed/5035bab20c83c0dca4a6ee80eb3b6f70_1_pr..jpg",
            "content/group_C/Jiayu Sun/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Jinglei Xu": [
            "./extra/week_1.png",
            "content/group_C/Jinglei Xu/week_1/processed/1689408983684_pr..png",
            "content/group_C/Jinglei Xu/week_1/processed/1689409222736_pr..png",
            "./extra/foo_week_1.png",
            "content/group_C/Jinglei Xu/week_1/processed/887eb20e9f57677d559add83a5e1c0d2_1_pr..jpg",
            "content/group_C/Jinglei Xu/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Xinyi Ding": [
            "./extra/week_1.png",
            "content/group_C/Xinyi Ding/week_1/processed/i10_pr..png",
            "content/group_C/Xinyi Ding/week_1/processed/i11_pr..png",
            "content/group_C/Xinyi Ding/week_1/processed/i12_pr..png",
            "content/group_C/Xinyi Ding/week_1/processed/i13_pr..png",
            "content/group_C/Xinyi Ding/week_1/processed/\u56fe\u7247_pr..png",
            "./extra/foo_week_1.png",
            "content/group_C/Xinyi Ding/week_1/processed/introduction_pr.png",
            "content/group_C/Xinyi Ding/week_1/processed/\u56fe\u7247_pr..png",
            "./extra/ref_week_1.png"
        ],
        "Xuejiao MA": [
            "./extra/week_1.png",
            "content/group_C/Xuejiao MA/week_1/processed/Screenshot 2023-07-15 at 10.37.27_pr..png",
            "content/group_C/Xuejiao MA/week_1/processed/Screenshot 2023-07-15 at 10.39.01_pr..png",
            "content/group_C/Xuejiao MA/week_1/processed/Screenshot 2023-07-15 at 10.40.06_pr..png",
            "content/group_C/Xuejiao MA/week_1/processed/WechatIMG3159_pr..jpeg",
            "content/group_C/Xuejiao MA/week_1/processed/WechatIMG3160_pr..jpeg",
            "content/group_C/Xuejiao MA/week_1/processed/WechatIMG3166_pr..jpeg",
            "./extra/foo_week_1.png",
            "content/group_C/Xuejiao MA/week_1/processed/DSC04645_pr..jpg",
            "content/group_C/Xuejiao MA/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Yue Qi": [
            "./extra/week_1.png",
            "content/group_C/Yue Qi/week_1/processed/i15_pr..png",
            "content/group_C/Yue Qi/week_1/processed/i16_pr..png",
            "content/group_C/Yue Qi/week_1/processed/i17_pr..png",
            "content/group_C/Yue Qi/week_1/processed/i18_pr..png",
            "content/group_C/Yue Qi/week_1/processed/i19_pr..png",
            "content/group_C/Yue Qi/week_1/processed/i20_pr..png",
            "content/group_C/Yue Qi/week_1/processed/i21_pr..png",
            "content/group_C/Yue Qi/week_1/processed/i22_pr..png",
            "./extra/foo_week_1.png",
            "content/group_C/Yue Qi/week_1/processed/b684df7853f5766b9b6269e29d2a711_pr..jpg",
            "content/group_C/Yue Qi/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Jiaxuan Zhou": [
            "./extra/week_1.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1941689354972_.pic_pr..jpg",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1951689354973_.pic_pr..jpg",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1961689354973_.pic_pr..jpg",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1971689354974_.pic_pr..jpg",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1991689355418_.pic_pr..jpg",
            "content/group_D/Jiaxuan Zhou/week_1/processed/2001689355419_.pic_pr..jpg",
            "content/group_D/Jiaxuan Zhou/week_1/processed/2011689355674_.pic_pr..jpg",
            "./extra/foo_week_1.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1861689353775_.pic_hd_pr..jpg",
            "content/group_D/Jiaxuan Zhou/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Wencheng Chan": [
            "./extra/week_1.png",
            "content/group_D/Wencheng Chan/week_1/processed/Dunhuang history collage_pr..jpg",
            "content/group_D/Wencheng Chan/week_1/processed/Elevation [\u8f6c\u6362](1)_1_pr..png",
            "content/group_D/Wencheng Chan/week_1/processed/rendering 1!_pr..png",
            "content/group_D/Wencheng Chan/week_1/processed/rendering 3\uff01_pr..png",
            "content/group_D/Wencheng Chan/week_1/processed/storyboard-1_pr..png",
            "content/group_D/Wencheng Chan/week_1/processed/\u6a21\u578b2_pr..png",
            "content/group_D/Wencheng Chan/week_1/processed/\u6a21\u578b_pr..png",
            "./extra/foo_week_1.png",
            "content/group_D/Wencheng Chan/week_1/processed/0b641114b2d769e98799d6a6154272e_pr..jpg",
            "content/group_D/Wencheng Chan/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Wenzhe Wang": [
            "./extra/week_1.png",
            "content/group_D/Wenzhe Wang/week_1/processed/i40_pr..png",
            "content/group_D/Wenzhe Wang/week_1/processed/i41_pr..png",
            "content/group_D/Wenzhe Wang/week_1/processed/i42_pr..png",
            "content/group_D/Wenzhe Wang/week_1/processed/i43_pr..png",
            "./extra/foo_week_1.png",
            "content/group_D/Wenzhe Wang/week_1/processed/5b7a99006a575700dd643aac1680fb3_pr..jpg",
            "content/group_D/Wenzhe Wang/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Yuqing Peng": [
            "./extra/week_1.png",
            "content/group_D/Yuqing Peng/week_1/processed/i30_pr..png",
            "content/group_D/Yuqing Peng/week_1/processed/i31_pr..png",
            "content/group_D/Yuqing Peng/week_1/processed/i32_pr..png",
            "content/group_D/Yuqing Peng/week_1/processed/i33_pr..png",
            "content/group_D/Yuqing Peng/week_1/processed/i34_pr..png",
            "content/group_D/Yuqing Peng/week_1/processed/i35_pr..png",
            "content/group_D/Yuqing Peng/week_1/processed/i36_pr..png",
            "./extra/foo_week_1.png",
            "content/group_D/Yuqing Peng/week_1/processed/ba509cf8e055f26255729acc77c3015_pr..jpg",
            "content/group_D/Yuqing Peng/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ]
    },
    "group_A": {
        "Anan MA": [
            "./extra/week_1.png",
            "content/group_A/Anan MA/week_1/processed/2_pr..png",
            "content/group_A/Anan MA/week_1/processed/3_pr..png",
            "content/group_A/Anan MA/week_1/processed/4_pr..png",
            "content/group_A/Anan MA/week_1/processed/5_pr..png",
            "content/group_A/Anan MA/week_1/processed/11_pr..png",
            "content/group_A/Anan MA/week_1/processed/Untitled-1_pr..jpg",
            "content/group_A/Anan MA/week_1/processed/Untitled-12_pr..png",
            "./extra/foo_week_1.png",
            "content/group_A/Anan MA/week_1/processed/b90cad34846b33ddd1e7620c0dbaa41_pr..png",
            "content/group_A/Anan MA/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Beining Zhang": [
            "./extra/week_1.png",
            "content/group_A/Beining Zhang/week_1/processed/3721cb3a5a9c3d051aeb00f2a9b0547_pr..png",
            "content/group_A/Beining Zhang/week_1/processed/c7f32408a681ea0f4359f74711cf62d_pr..png",
            "content/group_A/Beining Zhang/week_1/processed/ee270ce8860f597366b0ca303cf2997_pr..png",
            "content/group_A/Beining Zhang/week_1/processed/f1766f061879f376a7537210bd37c18_pr..png",
            "./extra/foo_week_1.png",
            "content/group_A/Beining Zhang/week_1/processed/d1e28f589c0bca6bee9cefaf08dc712_pr..jpg",
            "content/group_A/Beining Zhang/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Guangyao Cao": [
            "./extra/week_1.png",
            "content/group_A/Guangyao Cao/week_1/processed/image2_pr..png",
            "content/group_A/Guangyao Cao/week_1/processed/image_pr..png",
            "content/group_A/Guangyao Cao/week_1/processed/img3_pr..png",
            "content/group_A/Guangyao Cao/week_1/processed/img4_pr..png",
            "content/group_A/Guangyao Cao/week_1/processed/img5_pr..png",
            "content/group_A/Guangyao Cao/week_1/processed/img6_pr..png",
            "content/group_A/Guangyao Cao/week_1/processed/img7_pr..png",
            "./extra/foo_week_1.png",
            "content/group_A/Guangyao Cao/week_1/processed/introduction_pr.png",
            "content/group_A/Guangyao Cao/week_1/processed/\u5fae\u4fe1\u56fe\u7247_20220217151510_pr..jpg",
            "./extra/ref_week_1.png"
        ],
        "Yitong Xie": [
            "./extra/week_1.png",
            "content/group_A/Yitong Xie/week_1/processed/1_pr..jpg",
            "content/group_A/Yitong Xie/week_1/processed/2_pr..jpg",
            "content/group_A/Yitong Xie/week_1/processed/dinnimg - \u526f\u672c_pr..png",
            "content/group_A/Yitong Xie/week_1/processed/front_pr..png",
            "content/group_A/Yitong Xie/week_1/processed/s_pr..png",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-2_pr..jpg",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-22_pr..jpg",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-23_pr..jpg",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-24_pr..jpg",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-25_pr..jpg",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-2222_pr..jpg",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-2333_pr..jpg",
            "./extra/foo_week_1.png",
            "content/group_A/Yitong Xie/week_1/processed/introduction_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u5fae\u4fe1\u56fe\u7247_20230715151239_pr..jpg",
            "./extra/ref_week_1.png"
        ],
        "Yuxin Zhou": [
            "./extra/week_1.png",
            "content/group_A/Yuxin Zhou/week_1/processed/i2_pr..png",
            "content/group_A/Yuxin Zhou/week_1/processed/i3_pr..png",
            "content/group_A/Yuxin Zhou/week_1/processed/i4_pr..png",
            "content/group_A/Yuxin Zhou/week_1/processed/image_pr..png",
            "./extra/foo_week_1.png",
            "content/group_A/Yuxin Zhou/week_1/processed/d0e710c98440073df6ab70d4fee052a_pr..jpg",
            "content/group_A/Yuxin Zhou/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ]
    },
    "group_B": {
        "Deling Han": [
            "./extra/week_1.png",
            "content/group_B/Deling Han/week_1/processed/4e00c738eda32361cad5fd2a2232190_pr..png",
            "content/group_B/Deling Han/week_1/processed/46d29502859720bfde64c034e3cc2d8_pr..png",
            "content/group_B/Deling Han/week_1/processed/56e6a58851b67a9f1ab0a4f22b32436_pr..png",
            "content/group_B/Deling Han/week_1/processed/89dd8352e550dd55eae4ec0ae1eef95_pr..png",
            "content/group_B/Deling Han/week_1/processed/e1aef1425f4706180a44dca9d590c04_pr..png",
            "content/group_B/Deling Han/week_1/processed/e6b48c4807659b82e67f2ec0d0dddf6_pr..png",
            "./extra/foo_week_1.png",
            "content/group_B/Deling Han/week_1/processed/843136be438e87d628f9e240407bf4d_pr..jpg",
            "content/group_B/Deling Han/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Junren  Xian": [
            "./extra/week_1.png",
            "content/group_B/Junren  Xian/week_1/processed/\u5e7b\u706f\u72471_pr..PNG",
            "content/group_B/Junren  Xian/week_1/processed/\u5e7b\u706f\u72472_pr..PNG",
            "./extra/foo_week_1.png",
            "content/group_B/Junren  Xian/week_1/processed/88c929c2ea822d00937e7807557326a_pr..jpg",
            "content/group_B/Junren  Xian/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Shutong Guo": [
            "./extra/week_1.png",
            "content/group_B/Shutong Guo/week_1/processed/6c74d47ad19fa90f9cdba3e2883c9df_pr..png",
            "content/group_B/Shutong Guo/week_1/processed/dee117d1beccb8692c7c41766f5379e_pr..jpg",
            "./extra/foo_week_1.png",
            "content/group_B/Shutong Guo/week_1/processed/07a689347e9a41b0ec9ef5758210a10_pr..jpg",
            "content/group_B/Shutong Guo/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Wenxin Dai": [
            "./extra/week_1.png",
            "content/group_B/Wenxin Dai/week_1/processed/43a556224f29446a65e8c0fb5a8f4f7_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/191b998cee21ba2ed849b3e19dfe014_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/661998a365505a328d4916270a60987_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/243926565802691657_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/386026712471590118_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/410194747653042432_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/BIRKENHEAD FUTURE PLAN_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/adfd296495a366b3374eff6f4eff84f_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/babac12bb3d4b57821210ce5c87fcdf_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/c4b8ca337985b340d667abcd55a2846_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/d96a5f912e39c1d351930fc23e71b93_pr..png",
            "content/group_B/Wenxin Dai/week_1/processed/ea797b6b8d728c8a47a48295570cf6d_pr..png",
            "./extra/foo_week_1.png",
            "content/group_B/Wenxin Dai/week_1/processed/587438218396611271_pr..jpg",
            "content/group_B/Wenxin Dai/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Xinrui Ni": [
            "./extra/week_1.png",
            "content/group_B/Xinrui Ni/week_1/processed/2_pr..png",
            "content/group_B/Xinrui Ni/week_1/processed/4_pr..png",
            "content/group_B/Xinrui Ni/week_1/processed/i4_pr..png",
            "content/group_B/Xinrui Ni/week_1/processed/\u672a\u6807\u9898-1_pr..png",
            "./extra/foo_week_1.png",
            "content/group_B/Xinrui Ni/week_1/processed/IMG_0012(20230219-194931)_pr..JPG",
            "content/group_B/Xinrui Ni/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ]
    },
    "group_C": {
        "Jiayu Sun": [
            "./extra/week_1.png",
            "content/group_C/Jiayu Sun/week_1/processed/i7_pr..png",
            "content/group_C/Jiayu Sun/week_1/processed/i8_pr..png",
            "content/group_C/Jiayu Sun/week_1/processed/i9_pr..png",
            "./extra/foo_week_1.png",
            "content/group_C/Jiayu Sun/week_1/processed/5035bab20c83c0dca4a6ee80eb3b6f70_1_pr..jpg",
            "content/group_C/Jiayu Sun/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Jinglei Xu": [
            "./extra/week_1.png",
            "content/group_C/Jinglei Xu/week_1/processed/1689408983684_pr..png",
            "content/group_C/Jinglei Xu/week_1/processed/1689409222736_pr..png",
            "./extra/foo_week_1.png",
            "content/group_C/Jinglei Xu/week_1/processed/887eb20e9f57677d559add83a5e1c0d2_1_pr..jpg",
            "content/group_C/Jinglei Xu/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Xinyi Ding": [
            "./extra/week_1.png",
            "content/group_C/Xinyi Ding/week_1/processed/i10_pr..png",
            "content/group_C/Xinyi Ding/week_1/processed/i11_pr..png",
            "content/group_C/Xinyi Ding/week_1/processed/i12_pr..png",
            "content/group_C/Xinyi Ding/week_1/processed/i13_pr..png",
            "content/group_C/Xinyi Ding/week_1/processed/\u56fe\u7247_pr..png",
            "./extra/foo_week_1.png",
            "content/group_C/Xinyi Ding/week_1/processed/introduction_pr.png",
            "content/group_C/Xinyi Ding/week_1/processed/\u56fe\u7247_pr..png",
            "./extra/ref_week_1.png"
        ],
        "Xuejiao MA": [
            "./extra/week_1.png",
            "content/group_C/Xuejiao MA/week_1/processed/Screenshot 2023-07-15 at 10.37.27_pr..png",
            "content/group_C/Xuejiao MA/week_1/processed/Screenshot 2023-07-15 at 10.39.01_pr..png",
            "content/group_C/Xuejiao MA/week_1/processed/Screenshot 2023-07-15 at 10.40.06_pr..png",
            "content/group_C/Xuejiao MA/week_1/processed/WechatIMG3159_pr..jpeg",
            "content/group_C/Xuejiao MA/week_1/processed/WechatIMG3160_pr..jpeg",
            "content/group_C/Xuejiao MA/week_1/processed/WechatIMG3166_pr..jpeg",
            "./extra/foo_week_1.png",
            "content/group_C/Xuejiao MA/week_1/processed/DSC04645_pr..jpg",
            "content/group_C/Xuejiao MA/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Yue Qi": [
            "./extra/week_1.png",
            "content/group_C/Yue Qi/week_1/processed/i15_pr..png",
            "content/group_C/Yue Qi/week_1/processed/i16_pr..png",
            "content/group_C/Yue Qi/week_1/processed/i17_pr..png",
            "content/group_C/Yue Qi/week_1/processed/i18_pr..png",
            "content/group_C/Yue Qi/week_1/processed/i19_pr..png",
            "content/group_C/Yue Qi/week_1/processed/i20_pr..png",
            "content/group_C/Yue Qi/week_1/processed/i21_pr..png",
            "content/group_C/Yue Qi/week_1/processed/i22_pr..png",
            "./extra/foo_week_1.png",
            "content/group_C/Yue Qi/week_1/processed/b684df7853f5766b9b6269e29d2a711_pr..jpg",
            "content/group_C/Yue Qi/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ]
    },
    "group_D": {
        "Jiaxuan Zhou": [
            "./extra/week_1.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1941689354972_.pic_pr..jpg",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1951689354973_.pic_pr..jpg",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1961689354973_.pic_pr..jpg",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1971689354974_.pic_pr..jpg",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1991689355418_.pic_pr..jpg",
            "content/group_D/Jiaxuan Zhou/week_1/processed/2001689355419_.pic_pr..jpg",
            "content/group_D/Jiaxuan Zhou/week_1/processed/2011689355674_.pic_pr..jpg",
            "./extra/foo_week_1.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1861689353775_.pic_hd_pr..jpg",
            "content/group_D/Jiaxuan Zhou/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Wencheng Chan": [
            "./extra/week_1.png",
            "content/group_D/Wencheng Chan/week_1/processed/Dunhuang history collage_pr..jpg",
            "content/group_D/Wencheng Chan/week_1/processed/Elevation [\u8f6c\u6362](1)_1_pr..png",
            "content/group_D/Wencheng Chan/week_1/processed/rendering 1!_pr..png",
            "content/group_D/Wencheng Chan/week_1/processed/rendering 3\uff01_pr..png",
            "content/group_D/Wencheng Chan/week_1/processed/storyboard-1_pr..png",
            "content/group_D/Wencheng Chan/week_1/processed/\u6a21\u578b2_pr..png",
            "content/group_D/Wencheng Chan/week_1/processed/\u6a21\u578b_pr..png",
            "./extra/foo_week_1.png",
            "content/group_D/Wencheng Chan/week_1/processed/0b641114b2d769e98799d6a6154272e_pr..jpg",
            "content/group_D/Wencheng Chan/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Wenzhe Wang": [
            "./extra/week_1.png",
            "content/group_D/Wenzhe Wang/week_1/processed/i40_pr..png",
            "content/group_D/Wenzhe Wang/week_1/processed/i41_pr..png",
            "content/group_D/Wenzhe Wang/week_1/processed/i42_pr..png",
            "content/group_D/Wenzhe Wang/week_1/processed/i43_pr..png",
            "./extra/foo_week_1.png",
            "content/group_D/Wenzhe Wang/week_1/processed/5b7a99006a575700dd643aac1680fb3_pr..jpg",
            "content/group_D/Wenzhe Wang/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ],
        "Yuqing Peng": [
            "./extra/week_1.png",
            "content/group_D/Yuqing Peng/week_1/processed/i30_pr..png",
            "content/group_D/Yuqing Peng/week_1/processed/i31_pr..png",
            "content/group_D/Yuqing Peng/week_1/processed/i32_pr..png",
            "content/group_D/Yuqing Peng/week_1/processed/i33_pr..png",
            "content/group_D/Yuqing Peng/week_1/processed/i34_pr..png",
            "content/group_D/Yuqing Peng/week_1/processed/i35_pr..png",
            "content/group_D/Yuqing Peng/week_1/processed/i36_pr..png",
            "./extra/foo_week_1.png",
            "content/group_D/Yuqing Peng/week_1/processed/ba509cf8e055f26255729acc77c3015_pr..jpg",
            "content/group_D/Yuqing Peng/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png"
        ]
    }
}