var groups = {
    "theCityAndtheCity": {
        "dummy_name": [
            "./extra/dummy_week.png",
            "content/dummy_group/dummy_name/dummy_week/processed/references_pr.png",
            "content/dummy_group/dummy_name/dummy_week/processed/star_wars_all_terrain_scout_pr.png",
            "content/dummy_group/dummy_name/dummy_week/processed/syd_mead1_pr.png",
            "content/dummy_group/dummy_name/dummy_week/processed/update_pr.png",
            "content/dummy_group/dummy_name/dummy_week/processed/video_dune_pr.png",
            "content/dummy_group/dummy_name/dummy_week/processed/x.gif_preProcessed_long_.png",
            "./extra/foo_dummy_week.png",
            "content/dummy_group/dummy_name/dummy_week/processed/intro_pr.png",
            "content/dummy_group/dummy_name/dummy_week/processed/star_wars_all_terrain_scout_pr.png",
            "content/dummy_group/dummy_name/dummy_week/processed/syd_mead1_pr.png",
            "content/dummy_group/dummy_name/dummy_week/processed/x.gif_preProcessed_long_.png",
            "./extra/ref_dummy_week.png"
        ],
        "Anan MA": [
            "./extra/week_1.png",
            "content/group_A/Anan MA/week_1/processed/2_pr.png",
            "content/group_A/Anan MA/week_1/processed/3_pr.png",
            "content/group_A/Anan MA/week_1/processed/4_pr.png",
            "content/group_A/Anan MA/week_1/processed/5_pr.png",
            "content/group_A/Anan MA/week_1/processed/11_pr.png",
            "content/group_A/Anan MA/week_1/processed/Untitled-1_pr.png",
            "content/group_A/Anan MA/week_1/processed/Untitled-12_pr.png",
            "./extra/foo_week_1.png",
            "content/group_A/Anan MA/week_1/processed/b90cad34846b33ddd1e7620c0dbaa41_pr.png",
            "content/group_A/Anan MA/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ],
        "Beining Zhang": [
            "./extra/week_1.png",
            "content/group_A/Beining Zhang/week_1/processed/3721cb3a5a9c3d051aeb00f2a9b0547_pr.png",
            "content/group_A/Beining Zhang/week_1/processed/c7f32408a681ea0f4359f74711cf62d_pr.png",
            "content/group_A/Beining Zhang/week_1/processed/ee270ce8860f597366b0ca303cf2997_pr.png",
            "content/group_A/Beining Zhang/week_1/processed/f1766f061879f376a7537210bd37c18_pr.png",
            "./extra/foo_week_1.png",
            "content/group_A/Beining Zhang/week_1/processed/d1e28f589c0bca6bee9cefaf08dc712_pr.png",
            "content/group_A/Beining Zhang/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ],
        "Guangyao Cao": [
            "./extra/week_1.png",
            "content/group_A/Guangyao Cao/week_1/processed/image2_pr.png",
            "content/group_A/Guangyao Cao/week_1/processed/image_pr.png",
            "content/group_A/Guangyao Cao/week_1/processed/img3_pr.png",
            "content/group_A/Guangyao Cao/week_1/processed/img4_pr.png",
            "content/group_A/Guangyao Cao/week_1/processed/img5_pr.png",
            "content/group_A/Guangyao Cao/week_1/processed/img6_pr.png",
            "content/group_A/Guangyao Cao/week_1/processed/img7_pr.png",
            "./extra/foo_week_1.png",
            "content/group_A/Guangyao Cao/week_1/processed/introduction_pr.png",
            "content/group_A/Guangyao Cao/week_1/processed/\u5fae\u4fe1\u56fe\u7247_20220217151510_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_A/Guangyao Cao/week_2/processed/Unit1 GroupA Video Alien_pr.png",
            "./extra/ref_week_2.png"
        ],
        "Yitong Xie": [
            "./extra/week_1.png",
            "content/group_A/Yitong Xie/week_1/processed/1_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/2_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/dinnimg - \u526f\u672c_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/front_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/s_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-2_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-22_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-23_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-24_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-25_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-2222_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-2333_pr.png",
            "./extra/foo_week_1.png",
            "content/group_A/Yitong Xie/week_1/processed/introduction_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u5fae\u4fe1\u56fe\u7247_20230715151239_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ],
        "Yuxin Zhou": [
            "./extra/week_1.png",
            "content/group_A/Yuxin Zhou/week_1/processed/i2_pr.png",
            "content/group_A/Yuxin Zhou/week_1/processed/i3_pr.png",
            "content/group_A/Yuxin Zhou/week_1/processed/i4_pr.png",
            "content/group_A/Yuxin Zhou/week_1/processed/image_pr.png",
            "./extra/foo_week_1.png",
            "content/group_A/Yuxin Zhou/week_1/processed/d0e710c98440073df6ab70d4fee052a_pr.png",
            "content/group_A/Yuxin Zhou/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ],
        "Deling Han": [
            "./extra/week_1.png",
            "content/group_B/Deling Han/week_1/processed/4e00c738eda32361cad5fd2a2232190_pr.png",
            "content/group_B/Deling Han/week_1/processed/46d29502859720bfde64c034e3cc2d8_pr.png",
            "content/group_B/Deling Han/week_1/processed/56e6a58851b67a9f1ab0a4f22b32436_pr.png",
            "content/group_B/Deling Han/week_1/processed/89dd8352e550dd55eae4ec0ae1eef95_pr.png",
            "content/group_B/Deling Han/week_1/processed/e1aef1425f4706180a44dca9d590c04_pr.png",
            "content/group_B/Deling Han/week_1/processed/e6b48c4807659b82e67f2ec0d0dddf6_pr.png",
            "./extra/foo_week_1.png",
            "content/group_B/Deling Han/week_1/processed/843136be438e87d628f9e240407bf4d_pr.png",
            "content/group_B/Deling Han/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_B/Deling Han/week_2/processed/2dfb7a0453ab3b7c18a9c9f2cab0ec6_pr.png",
            "content/group_B/Deling Han/week_2/processed/3bba1da7d75bbdf77a63f4a77d650f4_pr.png",
            "content/group_B/Deling Han/week_2/processed/95dc618802ca6550bf2c0d1fe7a0c66_pr.png",
            "content/group_B/Deling Han/week_2/processed/a9c689bf0515607514c0b1a693a8a5e_pr.png",
            "content/group_B/Deling Han/week_2/processed/c69e2fb965bf36dbf8a2633c2b70f0f_pr.png",
            "content/group_B/Deling Han/week_2/processed/cf93f145400b6b27dc132db384a5e18_pr.png",
            "content/group_B/Deling Han/week_2/processed/e7a7f78ce85443e14730499ebbee9e5_pr.png",
            "content/group_B/Deling Han/week_2/processed/e45b87466d5dc58c80529b252c622c3_pr.png",
            "content/group_B/Deling Han/week_2/processed/video-dune_pr.png",
            "./extra/ref_week_2.png"
        ],
        "Junren  Xian": [
            "./extra/week_1.png",
            "content/group_B/Junren  Xian/week_1/processed/\u5e7b\u706f\u72471_pr.png",
            "content/group_B/Junren  Xian/week_1/processed/\u5e7b\u706f\u72472_pr.png",
            "./extra/foo_week_1.png",
            "content/group_B/Junren  Xian/week_1/processed/88c929c2ea822d00937e7807557326a_pr.png",
            "content/group_B/Junren  Xian/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ],
        "Shutong Guo": [
            "./extra/week_1.png",
            "content/group_B/Shutong Guo/week_1/processed/6c74d47ad19fa90f9cdba3e2883c9df_pr.png",
            "content/group_B/Shutong Guo/week_1/processed/dee117d1beccb8692c7c41766f5379e_pr.png",
            "./extra/foo_week_1.png",
            "content/group_B/Shutong Guo/week_1/processed/07a689347e9a41b0ec9ef5758210a10_pr.png",
            "content/group_B/Shutong Guo/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ],
        "Wenxin Dai": [
            "./extra/week_1.png",
            "content/group_B/Wenxin Dai/week_1/processed/43a556224f29446a65e8c0fb5a8f4f7_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/191b998cee21ba2ed849b3e19dfe014_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/661998a365505a328d4916270a60987_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/243926565802691657_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/386026712471590118_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/410194747653042432_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/BIRKENHEAD FUTURE PLAN_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/adfd296495a366b3374eff6f4eff84f_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/babac12bb3d4b57821210ce5c87fcdf_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/c4b8ca337985b340d667abcd55a2846_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/d96a5f912e39c1d351930fc23e71b93_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/ea797b6b8d728c8a47a48295570cf6d_pr.png",
            "./extra/foo_week_1.png",
            "content/group_B/Wenxin Dai/week_1/processed/587438218396611271_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ],
        "Xinrui Ni": [
            "./extra/week_1.png",
            "content/group_B/Xinrui Ni/week_1/processed/2_pr.png",
            "content/group_B/Xinrui Ni/week_1/processed/4_pr.png",
            "content/group_B/Xinrui Ni/week_1/processed/i4_pr.png",
            "content/group_B/Xinrui Ni/week_1/processed/\u672a\u6807\u9898-1_pr.png",
            "./extra/foo_week_1.png",
            "content/group_B/Xinrui Ni/week_1/processed/IMG_0012(20230219-194931)_pr.png",
            "content/group_B/Xinrui Ni/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_B/Xinrui Ni/week_2/processed/video_pr.png",
            "./extra/ref_week_2.png"
        ],
        "Jiayu Sun": [
            "./extra/week_1.png",
            "content/group_C/Jiayu Sun/week_1/processed/i7_pr.png",
            "content/group_C/Jiayu Sun/week_1/processed/i8_pr.png",
            "content/group_C/Jiayu Sun/week_1/processed/i9_pr.png",
            "./extra/foo_week_1.png",
            "content/group_C/Jiayu Sun/week_1/processed/5035bab20c83c0dca4a6ee80eb3b6f70_1_pr.png",
            "content/group_C/Jiayu Sun/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_C/Jiayu Sun/week_2/processed/arts_pr.png",
            "content/group_C/Jiayu Sun/week_2/processed/culture_pr.png",
            "content/group_C/Jiayu Sun/week_2/processed/dance&symbols_pr.png",
            "./extra/ref_week_2.png"
        ],
        "Jinglei Xu": [
            "./extra/week_1.png",
            "content/group_C/Jinglei Xu/week_1/processed/1689408983684_pr.png",
            "content/group_C/Jinglei Xu/week_1/processed/1689409222736_pr.png",
            "./extra/foo_week_1.png",
            "content/group_C/Jinglei Xu/week_1/processed/887eb20e9f57677d559add83a5e1c0d2_1_pr.png",
            "content/group_C/Jinglei Xu/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ],
        "Xinyi Ding": [
            "./extra/week_1.png",
            "content/group_C/Xinyi Ding/week_1/processed/i10_pr.png",
            "content/group_C/Xinyi Ding/week_1/processed/i11_pr.png",
            "content/group_C/Xinyi Ding/week_1/processed/i12_pr.png",
            "content/group_C/Xinyi Ding/week_1/processed/i13_pr.png",
            "content/group_C/Xinyi Ding/week_1/processed/\u56fe\u7247_pr.png",
            "./extra/foo_week_1.png",
            "content/group_C/Xinyi Ding/week_1/processed/introduction_pr.png",
            "content/group_C/Xinyi Ding/week_1/processed/\u56fe\u7247_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_C/Xinyi Ding/week_2/processed/1_pr.png",
            "content/group_C/Xinyi Ding/week_2/processed/2_pr.png",
            "content/group_C/Xinyi Ding/week_2/processed/3_pr.png",
            "content/group_C/Xinyi Ding/week_2/processed/4_pr.png",
            "./extra/ref_week_2.png"
        ],
        "Xuejiao MA": [
            "./extra/week_1.png",
            "content/group_C/Xuejiao MA/week_1/processed/Screenshot 2023-07-15 at 10.37.27_pr.png",
            "content/group_C/Xuejiao MA/week_1/processed/Screenshot 2023-07-15 at 10.39.01_pr.png",
            "content/group_C/Xuejiao MA/week_1/processed/Screenshot 2023-07-15 at 10.40.06_pr.png",
            "content/group_C/Xuejiao MA/week_1/processed/WechatIMG3159_pr.png",
            "content/group_C/Xuejiao MA/week_1/processed/WechatIMG3160_pr.png",
            "content/group_C/Xuejiao MA/week_1/processed/WechatIMG3166_pr.png",
            "./extra/foo_week_1.png",
            "content/group_C/Xuejiao MA/week_1/processed/DSC04645_pr.png",
            "content/group_C/Xuejiao MA/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_C/Xuejiao MA/week_2/processed/03_Minsky_The Society of Mind_pr_0_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/03_Minsky_The Society of Mind_pr_1_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/03_Minsky_The Society of Mind_pr_2_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/03_Minsky_The Society of Mind_pr_3_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/03_Minsky_The Society of Mind_pr_4_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/03_Minsky_The Society of Mind_pr_5_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/05_Nagakura et al $ Machines' Perception of Space_pr_0_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/05_Nagakura et al $ Machines' Perception of Space_pr_1_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/05_Nagakura et al $ Machines' Perception of Space_pr_2_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/05_Nagakura et al $ Machines' Perception of Space_pr_3_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/05_Nagakura et al $ Machines' Perception of Space_pr_4_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/05_Nagakura et al $ Machines' Perception of Space_pr_5_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/05_Nagakura et al $ Machines' Perception of Space_pr_6_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/05_Nagakura et al $ Machines' Perception of Space_pr_7_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_0_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_1_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_2_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_3_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_4_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_5_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_6_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_7_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_8_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_9_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_10_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_11_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_12_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_13_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_14_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_15_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_16_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_17_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_18_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_19_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_20_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_21_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_22_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_23_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_24_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_25_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_26_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_27_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_28_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_29_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_30_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_31_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_32_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_33_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_34_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_35_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_36_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_37_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_38_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_39_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_40_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_41_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_42_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_43_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_44_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_45_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_46_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_47_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_48_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_49_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_50_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_51_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_52_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_53_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_54_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_55_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_56_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_57_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_58_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_59_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_60_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_61_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_62_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_63_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_64_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_65_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_66_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_67_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_68_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_69_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_70_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_71_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_72_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_73_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_74_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_75_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_76_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_77_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_78_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_79_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_80_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_81_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_82_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_83_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_84_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_85_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_86_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_87_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_88_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_89_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_90_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_91_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_92_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_93_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_94_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_95_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_96_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_97_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_98_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_99_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_100_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_101_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_102_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/streetscore_paper_pr_0_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/streetscore_paper_pr_1_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/streetscore_paper_pr_2_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/streetscore_paper_pr_3_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/streetscore_paper_pr_4_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/streetscore_paper_pr_5_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/streetscore_paper_pr_6_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/theme analysis_pr.png",
            "./extra/ref_week_2.png"
        ],
        "Yue Qi": [
            "./extra/week_1.png",
            "content/group_C/Yue Qi/week_1/processed/i15_pr.png",
            "content/group_C/Yue Qi/week_1/processed/i16_pr.png",
            "content/group_C/Yue Qi/week_1/processed/i17_pr.png",
            "content/group_C/Yue Qi/week_1/processed/i18_pr.png",
            "content/group_C/Yue Qi/week_1/processed/i19_pr.png",
            "content/group_C/Yue Qi/week_1/processed/i20_pr.png",
            "content/group_C/Yue Qi/week_1/processed/i21_pr.png",
            "content/group_C/Yue Qi/week_1/processed/i22_pr.png",
            "./extra/foo_week_1.png",
            "content/group_C/Yue Qi/week_1/processed/b684df7853f5766b9b6269e29d2a711_pr.png",
            "content/group_C/Yue Qi/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_C/Yue Qi/week_2/processed/case study1_pr.png",
            "content/group_C/Yue Qi/week_2/processed/case study_pr.png",
            "content/group_C/Yue Qi/week_2/processed/yanomami nature_pr.png",
            "content/group_C/Yue Qi/week_2/processed/yanomami-culture_pr.png",
            "content/group_C/Yue Qi/week_2/processed/yanomami-external shock_pr.png",
            "./extra/ref_week_2.png"
        ],
        "Jiaxuan Zhou": [
            "./extra/week_1.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1941689354972_.pic_pr.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1951689354973_.pic_pr.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1961689354973_.pic_pr.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1971689354974_.pic_pr.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1991689355418_.pic_pr.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/2001689355419_.pic_pr.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/2011689355674_.pic_pr.png",
            "./extra/foo_week_1.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1861689353775_.pic_hd_pr.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ],
        "Wencheng Chan": [
            "./extra/week_1.png",
            "content/group_D/Wencheng Chan/week_1/processed/Dunhuang history collage_pr.png",
            "content/group_D/Wencheng Chan/week_1/processed/Elevation [\u8f6c\u6362](1)_1_pr.png",
            "content/group_D/Wencheng Chan/week_1/processed/rendering 1!_pr.png",
            "content/group_D/Wencheng Chan/week_1/processed/rendering 3\uff01_pr.png",
            "content/group_D/Wencheng Chan/week_1/processed/storyboard-1_pr.png",
            "content/group_D/Wencheng Chan/week_1/processed/\u6a21\u578b2_pr.png",
            "content/group_D/Wencheng Chan/week_1/processed/\u6a21\u578b_pr.png",
            "./extra/foo_week_1.png",
            "content/group_D/Wencheng Chan/week_1/processed/0b641114b2d769e98799d6a6154272e_pr.png",
            "content/group_D/Wencheng Chan/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_D/Wencheng Chan/week_2/processed/3d89ab0e21cc8b7317a15f42ce64f21_pr.png",
            "content/group_D/Wencheng Chan/week_2/processed/9eb82d4736aadad5278367954298d3d_pr.png",
            "content/group_D/Wencheng Chan/week_2/processed/37b6ff16c99a6bfb66527735b7b005d_pr.png",
            "content/group_D/Wencheng Chan/week_2/processed/53bd7d7de54b7668884aba2f2a6bb24_pr.png",
            "./extra/ref_week_2.png"
        ],
        "Wenzhe Wang": [
            "./extra/week_1.png",
            "content/group_D/Wenzhe Wang/week_1/processed/i40_pr.png",
            "content/group_D/Wenzhe Wang/week_1/processed/i41_pr.png",
            "content/group_D/Wenzhe Wang/week_1/processed/i42_pr.png",
            "content/group_D/Wenzhe Wang/week_1/processed/i43_pr.png",
            "./extra/foo_week_1.png",
            "content/group_D/Wenzhe Wang/week_1/processed/5b7a99006a575700dd643aac1680fb3_pr.png",
            "content/group_D/Wenzhe Wang/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_D/Wenzhe Wang/week_2/processed/\u5c4f\u5e55\u622a\u56fe 2023-07-26 075211_pr.png",
            "content/group_D/Wenzhe Wang/week_2/processed/\u5c4f\u5e55\u622a\u56fe 2023-07-27 144110_pr.png",
            "content/group_D/Wenzhe Wang/week_2/processed/\u5c4f\u5e55\u622a\u56fe 2023-07-27 144116_pr.png",
            "content/group_D/Wenzhe Wang/week_2/processed/\u5c4f\u5e55\u622a\u56fe 2023-07-27 144130_pr.png",
            "content/group_D/Wenzhe Wang/week_2/processed/\u5c4f\u5e55\u622a\u56fe 2023-07-27 144159_pr.png",
            "./extra/ref_week_2.png"
        ],
        "Yuqing Peng": [
            "./extra/week_1.png",
            "content/group_D/Yuqing Peng/week_1/processed/i30_pr.png",
            "content/group_D/Yuqing Peng/week_1/processed/i31_pr.png",
            "content/group_D/Yuqing Peng/week_1/processed/i32_pr.png",
            "content/group_D/Yuqing Peng/week_1/processed/i33_pr.png",
            "content/group_D/Yuqing Peng/week_1/processed/i34_pr.png",
            "content/group_D/Yuqing Peng/week_1/processed/i35_pr.png",
            "content/group_D/Yuqing Peng/week_1/processed/i36_pr.png",
            "./extra/foo_week_1.png",
            "content/group_D/Yuqing Peng/week_1/processed/ba509cf8e055f26255729acc77c3015_pr.png",
            "content/group_D/Yuqing Peng/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ]
    },
    "dummy_group": {
        "dummy_name": [
            "./extra/dummy_week.png",
            "content/dummy_group/dummy_name/dummy_week/processed/references_pr.png",
            "content/dummy_group/dummy_name/dummy_week/processed/star_wars_all_terrain_scout_pr.png",
            "content/dummy_group/dummy_name/dummy_week/processed/syd_mead1_pr.png",
            "content/dummy_group/dummy_name/dummy_week/processed/update_pr.png",
            "content/dummy_group/dummy_name/dummy_week/processed/video_dune_pr.png",
            "content/dummy_group/dummy_name/dummy_week/processed/x.gif_preProcessed_long_.png",
            "./extra/foo_dummy_week.png",
            "content/dummy_group/dummy_name/dummy_week/processed/intro_pr.png",
            "content/dummy_group/dummy_name/dummy_week/processed/star_wars_all_terrain_scout_pr.png",
            "content/dummy_group/dummy_name/dummy_week/processed/syd_mead1_pr.png",
            "content/dummy_group/dummy_name/dummy_week/processed/x.gif_preProcessed_long_.png",
            "./extra/ref_dummy_week.png"
        ]
    },
    "group_A": {
        "Anan MA": [
            "./extra/week_1.png",
            "content/group_A/Anan MA/week_1/processed/2_pr.png",
            "content/group_A/Anan MA/week_1/processed/3_pr.png",
            "content/group_A/Anan MA/week_1/processed/4_pr.png",
            "content/group_A/Anan MA/week_1/processed/5_pr.png",
            "content/group_A/Anan MA/week_1/processed/11_pr.png",
            "content/group_A/Anan MA/week_1/processed/Untitled-1_pr.png",
            "content/group_A/Anan MA/week_1/processed/Untitled-12_pr.png",
            "./extra/foo_week_1.png",
            "content/group_A/Anan MA/week_1/processed/b90cad34846b33ddd1e7620c0dbaa41_pr.png",
            "content/group_A/Anan MA/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ],
        "Beining Zhang": [
            "./extra/week_1.png",
            "content/group_A/Beining Zhang/week_1/processed/3721cb3a5a9c3d051aeb00f2a9b0547_pr.png",
            "content/group_A/Beining Zhang/week_1/processed/c7f32408a681ea0f4359f74711cf62d_pr.png",
            "content/group_A/Beining Zhang/week_1/processed/ee270ce8860f597366b0ca303cf2997_pr.png",
            "content/group_A/Beining Zhang/week_1/processed/f1766f061879f376a7537210bd37c18_pr.png",
            "./extra/foo_week_1.png",
            "content/group_A/Beining Zhang/week_1/processed/d1e28f589c0bca6bee9cefaf08dc712_pr.png",
            "content/group_A/Beining Zhang/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ],
        "Guangyao Cao": [
            "./extra/week_1.png",
            "content/group_A/Guangyao Cao/week_1/processed/image2_pr.png",
            "content/group_A/Guangyao Cao/week_1/processed/image_pr.png",
            "content/group_A/Guangyao Cao/week_1/processed/img3_pr.png",
            "content/group_A/Guangyao Cao/week_1/processed/img4_pr.png",
            "content/group_A/Guangyao Cao/week_1/processed/img5_pr.png",
            "content/group_A/Guangyao Cao/week_1/processed/img6_pr.png",
            "content/group_A/Guangyao Cao/week_1/processed/img7_pr.png",
            "./extra/foo_week_1.png",
            "content/group_A/Guangyao Cao/week_1/processed/introduction_pr.png",
            "content/group_A/Guangyao Cao/week_1/processed/\u5fae\u4fe1\u56fe\u7247_20220217151510_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_A/Guangyao Cao/week_2/processed/Unit1 GroupA Video Alien_pr.png",
            "./extra/ref_week_2.png"
        ],
        "Yitong Xie": [
            "./extra/week_1.png",
            "content/group_A/Yitong Xie/week_1/processed/1_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/2_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/dinnimg - \u526f\u672c_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/front_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/s_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-2_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-22_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-23_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-24_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-25_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-2222_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u672a\u547d\u540d-2333_pr.png",
            "./extra/foo_week_1.png",
            "content/group_A/Yitong Xie/week_1/processed/introduction_pr.png",
            "content/group_A/Yitong Xie/week_1/processed/\u5fae\u4fe1\u56fe\u7247_20230715151239_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ],
        "Yuxin Zhou": [
            "./extra/week_1.png",
            "content/group_A/Yuxin Zhou/week_1/processed/i2_pr.png",
            "content/group_A/Yuxin Zhou/week_1/processed/i3_pr.png",
            "content/group_A/Yuxin Zhou/week_1/processed/i4_pr.png",
            "content/group_A/Yuxin Zhou/week_1/processed/image_pr.png",
            "./extra/foo_week_1.png",
            "content/group_A/Yuxin Zhou/week_1/processed/d0e710c98440073df6ab70d4fee052a_pr.png",
            "content/group_A/Yuxin Zhou/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ]
    },
    "group_B": {
        "Deling Han": [
            "./extra/week_1.png",
            "content/group_B/Deling Han/week_1/processed/4e00c738eda32361cad5fd2a2232190_pr.png",
            "content/group_B/Deling Han/week_1/processed/46d29502859720bfde64c034e3cc2d8_pr.png",
            "content/group_B/Deling Han/week_1/processed/56e6a58851b67a9f1ab0a4f22b32436_pr.png",
            "content/group_B/Deling Han/week_1/processed/89dd8352e550dd55eae4ec0ae1eef95_pr.png",
            "content/group_B/Deling Han/week_1/processed/e1aef1425f4706180a44dca9d590c04_pr.png",
            "content/group_B/Deling Han/week_1/processed/e6b48c4807659b82e67f2ec0d0dddf6_pr.png",
            "./extra/foo_week_1.png",
            "content/group_B/Deling Han/week_1/processed/843136be438e87d628f9e240407bf4d_pr.png",
            "content/group_B/Deling Han/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_B/Deling Han/week_2/processed/2dfb7a0453ab3b7c18a9c9f2cab0ec6_pr.png",
            "content/group_B/Deling Han/week_2/processed/3bba1da7d75bbdf77a63f4a77d650f4_pr.png",
            "content/group_B/Deling Han/week_2/processed/95dc618802ca6550bf2c0d1fe7a0c66_pr.png",
            "content/group_B/Deling Han/week_2/processed/a9c689bf0515607514c0b1a693a8a5e_pr.png",
            "content/group_B/Deling Han/week_2/processed/c69e2fb965bf36dbf8a2633c2b70f0f_pr.png",
            "content/group_B/Deling Han/week_2/processed/cf93f145400b6b27dc132db384a5e18_pr.png",
            "content/group_B/Deling Han/week_2/processed/e7a7f78ce85443e14730499ebbee9e5_pr.png",
            "content/group_B/Deling Han/week_2/processed/e45b87466d5dc58c80529b252c622c3_pr.png",
            "content/group_B/Deling Han/week_2/processed/video-dune_pr.png",
            "./extra/ref_week_2.png"
        ],
        "Junren  Xian": [
            "./extra/week_1.png",
            "content/group_B/Junren  Xian/week_1/processed/\u5e7b\u706f\u72471_pr.png",
            "content/group_B/Junren  Xian/week_1/processed/\u5e7b\u706f\u72472_pr.png",
            "./extra/foo_week_1.png",
            "content/group_B/Junren  Xian/week_1/processed/88c929c2ea822d00937e7807557326a_pr.png",
            "content/group_B/Junren  Xian/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ],
        "Shutong Guo": [
            "./extra/week_1.png",
            "content/group_B/Shutong Guo/week_1/processed/6c74d47ad19fa90f9cdba3e2883c9df_pr.png",
            "content/group_B/Shutong Guo/week_1/processed/dee117d1beccb8692c7c41766f5379e_pr.png",
            "./extra/foo_week_1.png",
            "content/group_B/Shutong Guo/week_1/processed/07a689347e9a41b0ec9ef5758210a10_pr.png",
            "content/group_B/Shutong Guo/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ],
        "Wenxin Dai": [
            "./extra/week_1.png",
            "content/group_B/Wenxin Dai/week_1/processed/43a556224f29446a65e8c0fb5a8f4f7_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/191b998cee21ba2ed849b3e19dfe014_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/661998a365505a328d4916270a60987_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/243926565802691657_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/386026712471590118_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/410194747653042432_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/BIRKENHEAD FUTURE PLAN_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/adfd296495a366b3374eff6f4eff84f_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/babac12bb3d4b57821210ce5c87fcdf_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/c4b8ca337985b340d667abcd55a2846_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/d96a5f912e39c1d351930fc23e71b93_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/ea797b6b8d728c8a47a48295570cf6d_pr.png",
            "./extra/foo_week_1.png",
            "content/group_B/Wenxin Dai/week_1/processed/587438218396611271_pr.png",
            "content/group_B/Wenxin Dai/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ],
        "Xinrui Ni": [
            "./extra/week_1.png",
            "content/group_B/Xinrui Ni/week_1/processed/2_pr.png",
            "content/group_B/Xinrui Ni/week_1/processed/4_pr.png",
            "content/group_B/Xinrui Ni/week_1/processed/i4_pr.png",
            "content/group_B/Xinrui Ni/week_1/processed/\u672a\u6807\u9898-1_pr.png",
            "./extra/foo_week_1.png",
            "content/group_B/Xinrui Ni/week_1/processed/IMG_0012(20230219-194931)_pr.png",
            "content/group_B/Xinrui Ni/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_B/Xinrui Ni/week_2/processed/video_pr.png",
            "./extra/ref_week_2.png"
        ]
    },
    "group_C": {
        "Jiayu Sun": [
            "./extra/week_1.png",
            "content/group_C/Jiayu Sun/week_1/processed/i7_pr.png",
            "content/group_C/Jiayu Sun/week_1/processed/i8_pr.png",
            "content/group_C/Jiayu Sun/week_1/processed/i9_pr.png",
            "./extra/foo_week_1.png",
            "content/group_C/Jiayu Sun/week_1/processed/5035bab20c83c0dca4a6ee80eb3b6f70_1_pr.png",
            "content/group_C/Jiayu Sun/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_C/Jiayu Sun/week_2/processed/arts_pr.png",
            "content/group_C/Jiayu Sun/week_2/processed/culture_pr.png",
            "content/group_C/Jiayu Sun/week_2/processed/dance&symbols_pr.png",
            "./extra/ref_week_2.png"
        ],
        "Jinglei Xu": [
            "./extra/week_1.png",
            "content/group_C/Jinglei Xu/week_1/processed/1689408983684_pr.png",
            "content/group_C/Jinglei Xu/week_1/processed/1689409222736_pr.png",
            "./extra/foo_week_1.png",
            "content/group_C/Jinglei Xu/week_1/processed/887eb20e9f57677d559add83a5e1c0d2_1_pr.png",
            "content/group_C/Jinglei Xu/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ],
        "Xinyi Ding": [
            "./extra/week_1.png",
            "content/group_C/Xinyi Ding/week_1/processed/i10_pr.png",
            "content/group_C/Xinyi Ding/week_1/processed/i11_pr.png",
            "content/group_C/Xinyi Ding/week_1/processed/i12_pr.png",
            "content/group_C/Xinyi Ding/week_1/processed/i13_pr.png",
            "content/group_C/Xinyi Ding/week_1/processed/\u56fe\u7247_pr.png",
            "./extra/foo_week_1.png",
            "content/group_C/Xinyi Ding/week_1/processed/introduction_pr.png",
            "content/group_C/Xinyi Ding/week_1/processed/\u56fe\u7247_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_C/Xinyi Ding/week_2/processed/1_pr.png",
            "content/group_C/Xinyi Ding/week_2/processed/2_pr.png",
            "content/group_C/Xinyi Ding/week_2/processed/3_pr.png",
            "content/group_C/Xinyi Ding/week_2/processed/4_pr.png",
            "./extra/ref_week_2.png"
        ],
        "Xuejiao MA": [
            "./extra/week_1.png",
            "content/group_C/Xuejiao MA/week_1/processed/Screenshot 2023-07-15 at 10.37.27_pr.png",
            "content/group_C/Xuejiao MA/week_1/processed/Screenshot 2023-07-15 at 10.39.01_pr.png",
            "content/group_C/Xuejiao MA/week_1/processed/Screenshot 2023-07-15 at 10.40.06_pr.png",
            "content/group_C/Xuejiao MA/week_1/processed/WechatIMG3159_pr.png",
            "content/group_C/Xuejiao MA/week_1/processed/WechatIMG3160_pr.png",
            "content/group_C/Xuejiao MA/week_1/processed/WechatIMG3166_pr.png",
            "./extra/foo_week_1.png",
            "content/group_C/Xuejiao MA/week_1/processed/DSC04645_pr.png",
            "content/group_C/Xuejiao MA/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_C/Xuejiao MA/week_2/processed/03_Minsky_The Society of Mind_pr_0_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/03_Minsky_The Society of Mind_pr_1_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/03_Minsky_The Society of Mind_pr_2_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/03_Minsky_The Society of Mind_pr_3_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/03_Minsky_The Society of Mind_pr_4_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/03_Minsky_The Society of Mind_pr_5_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/05_Nagakura et al $ Machines' Perception of Space_pr_0_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/05_Nagakura et al $ Machines' Perception of Space_pr_1_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/05_Nagakura et al $ Machines' Perception of Space_pr_2_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/05_Nagakura et al $ Machines' Perception of Space_pr_3_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/05_Nagakura et al $ Machines' Perception of Space_pr_4_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/05_Nagakura et al $ Machines' Perception of Space_pr_5_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/05_Nagakura et al $ Machines' Perception of Space_pr_6_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/05_Nagakura et al $ Machines' Perception of Space_pr_7_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_0_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_1_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_2_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_3_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_4_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_5_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_6_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_7_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_8_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_9_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_10_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_11_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_12_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_13_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_14_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_15_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_16_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_17_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_18_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_19_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_20_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_21_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_22_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_23_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_24_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_25_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_26_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_27_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_28_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_29_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_30_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_31_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_32_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_33_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_34_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_35_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_36_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_37_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_38_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_39_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_40_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_41_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_42_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_43_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_44_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_45_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_46_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_47_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_48_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_49_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_50_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_51_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_52_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_53_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_54_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_55_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_56_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_57_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_58_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_59_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_60_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_61_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_62_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_63_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_64_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_65_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_66_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_67_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_68_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_69_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_70_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_71_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_72_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_73_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_74_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_75_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_76_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_77_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_78_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_79_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_80_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_81_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_82_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_83_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_84_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_85_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_86_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_87_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_88_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_89_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_90_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_91_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_92_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_93_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_94_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_95_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_96_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_97_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_98_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_99_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_100_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_101_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/1960_Kevin_Lynch_The_Image_of_The_City_book_pr_102_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/streetscore_paper_pr_0_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/streetscore_paper_pr_1_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/streetscore_paper_pr_2_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/streetscore_paper_pr_3_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/streetscore_paper_pr_4_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/streetscore_paper_pr_5_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/streetscore_paper_pr_6_alpha.png",
            "content/group_C/Xuejiao MA/week_2/processed/theme analysis_pr.png",
            "./extra/ref_week_2.png"
        ],
        "Yue Qi": [
            "./extra/week_1.png",
            "content/group_C/Yue Qi/week_1/processed/i15_pr.png",
            "content/group_C/Yue Qi/week_1/processed/i16_pr.png",
            "content/group_C/Yue Qi/week_1/processed/i17_pr.png",
            "content/group_C/Yue Qi/week_1/processed/i18_pr.png",
            "content/group_C/Yue Qi/week_1/processed/i19_pr.png",
            "content/group_C/Yue Qi/week_1/processed/i20_pr.png",
            "content/group_C/Yue Qi/week_1/processed/i21_pr.png",
            "content/group_C/Yue Qi/week_1/processed/i22_pr.png",
            "./extra/foo_week_1.png",
            "content/group_C/Yue Qi/week_1/processed/b684df7853f5766b9b6269e29d2a711_pr.png",
            "content/group_C/Yue Qi/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_C/Yue Qi/week_2/processed/case study1_pr.png",
            "content/group_C/Yue Qi/week_2/processed/case study_pr.png",
            "content/group_C/Yue Qi/week_2/processed/yanomami nature_pr.png",
            "content/group_C/Yue Qi/week_2/processed/yanomami-culture_pr.png",
            "content/group_C/Yue Qi/week_2/processed/yanomami-external shock_pr.png",
            "./extra/ref_week_2.png"
        ]
    },
    "group_D": {
        "Jiaxuan Zhou": [
            "./extra/week_1.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1941689354972_.pic_pr.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1951689354973_.pic_pr.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1961689354973_.pic_pr.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1971689354974_.pic_pr.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1991689355418_.pic_pr.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/2001689355419_.pic_pr.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/2011689355674_.pic_pr.png",
            "./extra/foo_week_1.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/1861689353775_.pic_hd_pr.png",
            "content/group_D/Jiaxuan Zhou/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ],
        "Wencheng Chan": [
            "./extra/week_1.png",
            "content/group_D/Wencheng Chan/week_1/processed/Dunhuang history collage_pr.png",
            "content/group_D/Wencheng Chan/week_1/processed/Elevation [\u8f6c\u6362](1)_1_pr.png",
            "content/group_D/Wencheng Chan/week_1/processed/rendering 1!_pr.png",
            "content/group_D/Wencheng Chan/week_1/processed/rendering 3\uff01_pr.png",
            "content/group_D/Wencheng Chan/week_1/processed/storyboard-1_pr.png",
            "content/group_D/Wencheng Chan/week_1/processed/\u6a21\u578b2_pr.png",
            "content/group_D/Wencheng Chan/week_1/processed/\u6a21\u578b_pr.png",
            "./extra/foo_week_1.png",
            "content/group_D/Wencheng Chan/week_1/processed/0b641114b2d769e98799d6a6154272e_pr.png",
            "content/group_D/Wencheng Chan/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_D/Wencheng Chan/week_2/processed/3d89ab0e21cc8b7317a15f42ce64f21_pr.png",
            "content/group_D/Wencheng Chan/week_2/processed/9eb82d4736aadad5278367954298d3d_pr.png",
            "content/group_D/Wencheng Chan/week_2/processed/37b6ff16c99a6bfb66527735b7b005d_pr.png",
            "content/group_D/Wencheng Chan/week_2/processed/53bd7d7de54b7668884aba2f2a6bb24_pr.png",
            "./extra/ref_week_2.png"
        ],
        "Wenzhe Wang": [
            "./extra/week_1.png",
            "content/group_D/Wenzhe Wang/week_1/processed/i40_pr.png",
            "content/group_D/Wenzhe Wang/week_1/processed/i41_pr.png",
            "content/group_D/Wenzhe Wang/week_1/processed/i42_pr.png",
            "content/group_D/Wenzhe Wang/week_1/processed/i43_pr.png",
            "./extra/foo_week_1.png",
            "content/group_D/Wenzhe Wang/week_1/processed/5b7a99006a575700dd643aac1680fb3_pr.png",
            "content/group_D/Wenzhe Wang/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "content/group_D/Wenzhe Wang/week_2/processed/\u5c4f\u5e55\u622a\u56fe 2023-07-26 075211_pr.png",
            "content/group_D/Wenzhe Wang/week_2/processed/\u5c4f\u5e55\u622a\u56fe 2023-07-27 144110_pr.png",
            "content/group_D/Wenzhe Wang/week_2/processed/\u5c4f\u5e55\u622a\u56fe 2023-07-27 144116_pr.png",
            "content/group_D/Wenzhe Wang/week_2/processed/\u5c4f\u5e55\u622a\u56fe 2023-07-27 144130_pr.png",
            "content/group_D/Wenzhe Wang/week_2/processed/\u5c4f\u5e55\u622a\u56fe 2023-07-27 144159_pr.png",
            "./extra/ref_week_2.png"
        ],
        "Yuqing Peng": [
            "./extra/week_1.png",
            "content/group_D/Yuqing Peng/week_1/processed/i30_pr.png",
            "content/group_D/Yuqing Peng/week_1/processed/i31_pr.png",
            "content/group_D/Yuqing Peng/week_1/processed/i32_pr.png",
            "content/group_D/Yuqing Peng/week_1/processed/i33_pr.png",
            "content/group_D/Yuqing Peng/week_1/processed/i34_pr.png",
            "content/group_D/Yuqing Peng/week_1/processed/i35_pr.png",
            "content/group_D/Yuqing Peng/week_1/processed/i36_pr.png",
            "./extra/foo_week_1.png",
            "content/group_D/Yuqing Peng/week_1/processed/ba509cf8e055f26255729acc77c3015_pr.png",
            "content/group_D/Yuqing Peng/week_1/processed/introduction_pr.png",
            "./extra/ref_week_1.png",
            "./extra/foo_week_2.png",
            "./extra/ref_week_2.png"
        ]
    }
}